spring:
  application:
     name: spring-boot-multiple-rabbit-mq
  rabbitmq1:
    host: 127.0.0.1
    port: 5672
    username: user1
    password: pass1
    virtual-host: /
  rabbitmq2:
    host: 127.0.0.1
    port: 5673
    username: user2
    password: pass2
    virtual-host: /

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: work.longxing.learn.springboot.rabbitmq.springbootmultiplerabbitmq.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
